server:
  port: 8763
  #context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: upp-shopping-message
    prefer-ip-address: true     #访问路径可以显示IP地址
spring:
  application:
    name: upp-shopping-message
  redis:
    host: 192.168.121.181
  ##activemq连接信息
  activemq:
    broker-url: tcp://192.168.121.181:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: zhenglongsu@163.com
    password: suzl504473410
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true

msg:
  subject: 蚂蚁课堂|每特教育提示您，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!蚂蚁课堂|每特教育 上海每特教育科技有限公司 www.itmayiedu.com


info:
  app.name: @project.artifactId@
  company.name: www.shopping.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@