package com.shopping.pay.mapper;


import com.shopping.api.pay.entities.PaymentInfo;
import com.shopping.api.pay.entities.PaymentInfoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    long countByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int insert(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int insertSelective(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    List<PaymentInfo> selectByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    PaymentInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentInfo record);
}