package com.shopping.pay.mapper;


import com.shopping.api.pay.entities.PaymentType;
import com.shopping.api.pay.entities.PaymentTypeExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PaymentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    long countByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int insert(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int insertSelective(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    List<PaymentType> selectByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    PaymentType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentType record);
}