package com.shopping.api.pay.entities;

import java.util.Date;

public class PaymentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.typeid
     *
     * @mbg.generated
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.orderid
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.platformorderid
     *
     * @mbg.generated
     */
    private String platformorderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.paymessage
     *
     * @mbg.generated
     */
    private String paymessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.txntime
     *
     * @mbg.generated
     */
    private Date txntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    public PaymentInfo(Long id, Integer userid, String typeid, String orderid, String platformorderid, String price, String source, String state, String paymessage, Date txntime, Date created, Date updated) {
        this.id = id;
        this.userid = userid;
        this.typeid = typeid;
        this.orderid = orderid;
        this.platformorderid = platformorderid;
        this.price = price;
        this.source = source;
        this.state = state;
        this.paymessage = paymessage;
        this.txntime = txntime;
        this.created = created;
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    public PaymentInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.id
     *
     * @return the value of payment_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.id
     *
     * @param id the value for payment_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.userid
     *
     * @return the value of payment_info.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.userid
     *
     * @param userid the value for payment_info.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.typeid
     *
     * @return the value of payment_info.typeid
     *
     * @mbg.generated
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.typeid
     *
     * @param typeid the value for payment_info.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.orderid
     *
     * @return the value of payment_info.orderid
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.orderid
     *
     * @param orderid the value for payment_info.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.platformorderid
     *
     * @return the value of payment_info.platformorderid
     *
     * @mbg.generated
     */
    public String getPlatformorderid() {
        return platformorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.platformorderid
     *
     * @param platformorderid the value for payment_info.platformorderid
     *
     * @mbg.generated
     */
    public void setPlatformorderid(String platformorderid) {
        this.platformorderid = platformorderid == null ? null : platformorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.price
     *
     * @return the value of payment_info.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.price
     *
     * @param price the value for payment_info.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.source
     *
     * @return the value of payment_info.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.source
     *
     * @param source the value for payment_info.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.state
     *
     * @return the value of payment_info.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.state
     *
     * @param state the value for payment_info.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.paymessage
     *
     * @return the value of payment_info.paymessage
     *
     * @mbg.generated
     */
    public String getPaymessage() {
        return paymessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.paymessage
     *
     * @param paymessage the value for payment_info.paymessage
     *
     * @mbg.generated
     */
    public void setPaymessage(String paymessage) {
        this.paymessage = paymessage == null ? null : paymessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.txntime
     *
     * @return the value of payment_info.txntime
     *
     * @mbg.generated
     */
    public Date getTxntime() {
        return txntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.txntime
     *
     * @param txntime the value for payment_info.txntime
     *
     * @mbg.generated
     */
    public void setTxntime(Date txntime) {
        this.txntime = txntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.created
     *
     * @return the value of payment_info.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.created
     *
     * @param created the value for payment_info.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.updated
     *
     * @return the value of payment_info.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.updated
     *
     * @param updated the value for payment_info.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", typeid=").append(typeid);
        sb.append(", orderid=").append(orderid);
        sb.append(", platformorderid=").append(platformorderid);
        sb.append(", price=").append(price);
        sb.append(", source=").append(source);
        sb.append(", state=").append(state);
        sb.append(", paymessage=").append(paymessage);
        sb.append(", txntime=").append(txntime);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}