package com.shopping.api.pay.entities;

import java.util.Date;

public class PaymentType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.typename
     *
     * @mbg.generated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.fronturl
     *
     * @mbg.generated
     */
    private String fronturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.backurl
     *
     * @mbg.generated
     */
    private String backurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.merchantid
     *
     * @mbg.generated
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_type.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    public PaymentType(Long id, String typename, String fronturl, String backurl, String merchantid, Date created, Date updated) {
        this.id = id;
        this.typename = typename;
        this.fronturl = fronturl;
        this.backurl = backurl;
        this.merchantid = merchantid;
        this.created = created;
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    public PaymentType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.id
     *
     * @return the value of payment_type.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.id
     *
     * @param id the value for payment_type.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.typename
     *
     * @return the value of payment_type.typename
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.typename
     *
     * @param typename the value for payment_type.typename
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.fronturl
     *
     * @return the value of payment_type.fronturl
     * @mbg.generated
     */
    public String getFronturl() {
        return fronturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.fronturl
     *
     * @param fronturl the value for payment_type.fronturl
     * @mbg.generated
     */
    public void setFronturl(String fronturl) {
        this.fronturl = fronturl == null ? null : fronturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.backurl
     *
     * @return the value of payment_type.backurl
     * @mbg.generated
     */
    public String getBackurl() {
        return backurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.backurl
     *
     * @param backurl the value for payment_type.backurl
     * @mbg.generated
     */
    public void setBackurl(String backurl) {
        this.backurl = backurl == null ? null : backurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.merchantid
     *
     * @return the value of payment_type.merchantid
     * @mbg.generated
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.merchantid
     *
     * @param merchantid the value for payment_type.merchantid
     * @mbg.generated
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid == null ? null : merchantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.created
     *
     * @return the value of payment_type.created
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.created
     *
     * @param created the value for payment_type.created
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_type.updated
     *
     * @return the value of payment_type.updated
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_type.updated
     *
     * @param updated the value for payment_type.updated
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", typename=").append(typename);
        sb.append(", fronturl=").append(fronturl);
        sb.append(", backurl=").append(backurl);
        sb.append(", merchantid=").append(merchantid);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}